apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../../base
- cronjob-sync-refresh.yaml

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 17d1b83394f8fed2a01e5cc8bc6fbdf35af5648e
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: 6a2bb2211f95ea3e08e6a15dcfe0e78c1548fe60
