#!/bin/bash
# Discover open component-onboarding Jira issues and generate a dynamic child
# pipeline YAML with one trigger job per issue.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${GENERATED_PIPELINE_FILE:-generated-child-pipelines.yml}"
JIRA_RESPONSE="/tmp/jira-response.json"

# --- Load shared libraries (provides install_acli, setup_acli_auth, print_*) ---
# shellcheck source=scripts/setup-agentic-lib.sh
source "$SCRIPT_DIR/setup-agentic-lib.sh"

# --- Preflight checks ---
print_step "Preflight checks"
fail=0

# acli.sh reads JIRA_EMAIL (or JIRA_USER); the project CI var is JIRA_USER_EMAIL.
export JIRA_EMAIL="${JIRA_EMAIL:-${JIRA_USER_EMAIL:-}}"

for var in JIRA_EMAIL JIRA_API_TOKEN JIRA_BASE_URL JIRA_PROJECT JIRA_PARENT_ISSUES JIRA_LABEL; do
  if [[ -z "${!var:-}" ]]; then
    print_error "$var is not set"
    fail=1
  else
    print_success "$var is set"
  fi
done
[[ "$fail" -eq 1 ]] && exit 1

# --- Install and authenticate acli ---
print_step "Installing Atlassian CLI (acli)"
install_acli

print_step "Authenticating acli against ${ACLI_JIRA_SITE:-redhat.atlassian.net}"
setup_acli_auth

# --- Build JQL ---
print_step "Building JQL query"

# Non-terminal statuses to exclude (covers all common Jira Cloud terminal states)
CLOSED_STATUSES='"Resolved","Closed","Done","Won'\''t Do","Cancelled","Rejected","Duplicate","Won'\''t Fix"'

# Build the "cloned from" predicate — one linkedIssues clause per parent key
# NOTE: Jira Cloud uses linkedIssues() not linkedIssuesOf() which is Server/DC only.
CLONE_CLAUSES=()
IFS=',' read -ra PARENTS <<< "$JIRA_PARENT_ISSUES"
for parent in "${PARENTS[@]}"; do
  parent="${parent// /}"  # trim whitespace
  CLONE_CLAUSES+=("issue in linkedIssues(\"${parent}\", \"is cloned by\")")
done
CLONE_JQL="$(printf '%s' "${CLONE_CLAUSES[0]}"; for clause in "${CLONE_CLAUSES[@]:1}"; do printf ' OR %s' "$clause"; done)"

# JIRA_PROJECT=RHODS
JQL="project = ${JIRA_PROJECT} AND status not in (${CLOSED_STATUSES}) AND labels = \"${JIRA_LABEL}\" AND (${CLONE_JQL})"

print_success "JQL: $JQL"

# --- Fetch issues via acli ---
print_step "Querying Jira for matching issues"
acli jira workitem search \
  --jql "$JQL" \
  --limit 200 \
  --json > "$JIRA_RESPONSE" || {
    print_error "acli jira workitem search failed. Check JQL syntax and credentials."
    exit 1
  }

ISSUE_KEYS=$(jq -r '.[].key // empty' "$JIRA_RESPONSE" 2>/dev/null || true)
ISSUE_COUNT=$(echo "$ISSUE_KEYS" | grep -c '\S' || true)
print_success "Found ${ISSUE_COUNT} matching issue(s)"

# --- Generate child pipeline YAML ---
print_step "Generating ${OUTPUT}"

if [[ "$ISSUE_COUNT" -eq 0 ]]; then
  print_warning "No issues found — emitting no-op pipeline"
  cat > "$OUTPUT" <<'YAML'
# No open component-onboarding issues found matching the search criteria.
stages:
  - notify

no-issues-found:
  stage: notify
  image: quay.io/fedora/fedora:latest
  tags:
    - aipcc-small-x86_64
  script:
    - echo "No open component-onboarding Jira issues found. Nothing to onboard."
YAML
  print_success "Written: $OUTPUT (no-op)"
  exit 0
fi

# Header
cat > "$OUTPUT" <<YAML
# Auto-generated by scripts/fetch-jira-issues.sh — do not edit manually.
# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Issues: ${ISSUE_COUNT}

stages:
  - trigger

YAML

# One trigger job per issue
while IFS= read -r key; do
  [[ -z "$key" ]] && continue
  jira_url="${JIRA_BASE_URL}/browse/${key}"
  job_name="trigger-${key}"

  cat >> "$OUTPUT" <<YAML
${job_name}:
  stage: trigger
  variables:
    JIRA_URL: "${jira_url}"
  trigger:
    include:
      - local: child-pipeline.yml
    strategy: depend

YAML
  print_success "  Added trigger job for ${key} → ${jira_url}"
done <<< "$ISSUE_KEYS"

print_success "Generated ${OUTPUT} with ${ISSUE_COUNT} trigger job(s)"
